### ISSUE TITLE
Compile Error for Android

### ISSUE THREAD

**Issue by myleshk** [souvik-ghosh/react-native-create-thumbnail#60]
**Describe the bug**
Cannot build for Android, got `Task :react-native-create-thumbnail:androidJavadoc FAILED`

**To Reproduce**
1. either `npm run android` or `./gradlew build` in `android` folder
2. tried `./gradlew clean` and even `rm -rf ~/.gradle/caches/*`, no effect.

**Version**
`react-native-create-thumbnail` version 1.5.1

**Expected Results**
Able to build.

**Snack, code example, screenshot, or link to a repository**
```
> Task :react-native-create-thumbnail:androidJavadoc
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:12: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.Arguments;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:13: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.GuardedResultAsyncTask;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:14: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.Promise;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:15: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactApplicationContext;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:16: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactContext;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:17: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactContextBaseJavaModule;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:18: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactMethod;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:19: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReadableMap;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:20: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.WritableMap;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:36: error: cannot find symbol
public class CreateThumbnailModule extends ReactContextBaseJavaModule {
                                           ^
  symbol: class ReactContextBaseJavaModule
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:38: error: cannot find symbol
    private final ReactApplicationContext reactContext;
                  ^
  symbol:   class ReactApplicationContext
  location: class CreateThumbnailModule
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:40: error: cannot find symbol
    public CreateThumbnailModule(ReactApplicationContext reactContext) {
                                 ^
  symbol:   class ReactApplicationContext
  location: class CreateThumbnailModule
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:51: error: cannot find symbol
    public void create(ReadableMap options, Promise promise) {
                       ^
  symbol:   class ReadableMap
  location: class CreateThumbnailModule
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:51: error: cannot find symbol
    public void create(ReadableMap options, Promise promise) {
                                            ^
  symbol:   class Promise
  location: class CreateThumbnailModule
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:55: error: cannot find symbol
    private static class ProcessDataTask extends GuardedResultAsyncTask<ReadableMap> {
                                                 ^
  symbol:   class GuardedResultAsyncTask
  location: class CreateThumbnailModule
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:55: error: cannot find symbol
    private static class ProcessDataTask extends GuardedResultAsyncTask<ReadableMap> {
                                                                        ^
  symbol:   class ReadableMap
  location: class CreateThumbnailModule
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:57: error: cannot find symbol
        private final Promise promise;
                      ^
  symbol:   class Promise
  location: class ProcessDataTask
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:58: error: cannot find symbol
        private final ReadableMap options;
                      ^
  symbol:   class ReadableMap
  location: class ProcessDataTask
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:60: error: cannot find symbol
        protected ProcessDataTask(ReactContext reactContext, Promise promise, ReadableMap options) {
                                  ^
  symbol:   class ReactContext
  location: class ProcessDataTask
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:60: error: cannot find symbol
        protected ProcessDataTask(ReactContext reactContext, Promise promise, ReadableMap options) {
                                                             ^
  symbol:   class Promise
  location: class ProcessDataTask
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:60: error: cannot find symbol
        protected ProcessDataTask(ReactContext reactContext, Promise promise, ReadableMap options) {
                                                                              ^
  symbol:   class ReadableMap
  location: class ProcessDataTask
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:68: error: cannot find symbol
        protected ReadableMap doInBackgroundGuarded() {
                  ^
  symbol:   class ReadableMap
  location: class ProcessDataTask
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:132: error: cannot find symbol
        protected void onPostExecuteGuarded(ReadableMap readableArray) {
                                            ^
  symbol:   class ReadableMap
  location: class ProcessDataTask
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:7: error: package com.facebook.react does not exist
import com.facebook.react.ReactPackage;
                         ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:8: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.NativeModule;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:9: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.ReactApplicationContext;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:10: error: package com.facebook.react.uimanager does not exist
import com.facebook.react.uimanager.ViewManager;
                                   ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:11: error: package com.facebook.react.bridge does not exist
import com.facebook.react.bridge.JavaScriptModule;
                                ^
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:13: error: cannot find symbol
public class CreateThumbnailPackage implements ReactPackage {
                                               ^
  symbol: class ReactPackage
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:15: error: cannot find symbol
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
                                                  ^
  symbol:   class ReactApplicationContext
  location: class CreateThumbnailPackage
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:15: error: cannot find symbol
    public List<NativeModule> createNativeModules(ReactApplicationContext reactContext) {
                ^
  symbol:   class NativeModule
  location: class CreateThumbnailPackage
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:20: error: cannot find symbol
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
                                                ^
  symbol:   class ReactApplicationContext
  location: class CreateThumbnailPackage
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailPackage.java:20: error: cannot find symbol
    public List<ViewManager> createViewManagers(ReactApplicationContext reactContext) {
                ^
  symbol:   class ViewManager
  location: class CreateThumbnailPackage
/Users/username/projects/react-native-melcotoday-app-client/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java:50: error: cannot find symbol
    @ReactMethod
     ^
  symbol:   class ReactMethod
  location: class CreateThumbnailModule
34 errors

> Task :react-native-create-thumbnail:androidJavadoc FAILED
```

**Comment by hamedhemmati** [comment]
I had to add maven { url "https://jcenter.bintray.com" } to allprojects repositories in the build.gradle for it to build properly.

**Comment by demedos** [comment]
> I had to add maven { url "https://jcenter.bintray.com" } to allprojects repositories in the build.gradle for it to build properly.

@hamedhemmati  mind opening a PR with the changes?

**Comment by souvik-ghosh** [comment]
This should work in v1.6.0

**Comment by Bimbimz** [comment]
i have this problem.
iam use v1.6.3 in "react-native": "0.70.1"
adding maven no change.
what is the solution?

**Comment by fukemy** [comment]
not working again in 1.6.3

**Comment by fukemy** [comment]
bintray is dead
