### ISSUE TITLE
Not able to compile on XCode 12.5

### ISSUE THREAD

**Issue by cfreact1** [souvik-ghosh/react-native-create-thumbnail#41]
While compiling on XCode 12.5 i get "Use of undeclared identifier 'data'
<img width="1768" alt="Screenshot 2021-05-24 at 11 40 54 AM" src="https://user-images.githubusercontent.com/84103117/119304482-eba38800-bc84-11eb-9964-b05fa9c10d95.png">
"
