### ISSUE TITLE
Not working on Android , RN Version 0.65.1

### ISSUE THREAD

**Issue by AlbinCederblad** [souvik-ghosh/react-native-create-thumbnail#71]
**Describe the bug**
Fresh install, only importing the module, this is what happens when running app:
```
BUILD FAILED in 12s

CreateThumbnailModule.java:194: error: exception java.io.IOException is never thrown in body of corresponding try statement
        } catch(IOException e) {

CreateThumbnailModule.java uses or overrides a deprecated API.

* What went wrong:
Execution failed for task ':react-native-create-thumbnail:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
```
**To Reproduce**
on android:
1. npm i react-native-create-thumbnail
2. start
3. run-android

**Version**
latest

Haven't added any code yet, so this is simply with a fresh install and importing the module.

**Comment by souvik-ghosh** [comment]
This got broken when the support for android 13 was added in v1.6.0. This library now requires android API level 10 or above. It's related to the change in the `MediaMetadataRetriever.release()` API (more info [here](https://developer.android.com/reference/android/media/MediaMetadataRetriever#release())).

@AlbinCederblad, The easiest solution for you would be to use v1.5.1 of this library. And to use the latest version, you can upgrade your project to react-native 69 or later, which will also upgrade the Gradle and android-build-tool versions.

I will add this to the release notes or probably publish release v2.0.0 as it's a breaking change.

**Comment by AlbinCederblad** [comment]
> This got broken when the support for android 13 was added in v1.6.0. This library now requires android API level 10 or above. It's related to the change in the `MediaMetadataRetriever.release()` API (more info [here](https://developer.android.com/reference/android/media/MediaMetadataRetriever#release())).
> 
> @AlbinCederblad, The easiest solution for you would be to use v1.5.1 of this library. And to use the latest version, you can upgrade your project to react-native 69 or later, which will also upgrade the Gradle and android-build-tool versions.
> 
> I will add this to the release notes or probably publish release v2.0.0 as it's a breaking change.

Thanks!

**Comment by cuteWarmFrog** [comment]
> This got broken when the support for android 13 was added in v1.6.0. This library now requires android API level 10 or above. It's related to the change in the `MediaMetadataRetriever.release()` API (more info [here](https://developer.android.com/reference/android/media/MediaMetadataRetriever#release())).
> 
> @AlbinCederblad, The easiest solution for you would be to use v1.5.1 of this library. And to use the latest version, you can upgrade your project to react-native 69 or later, which will also upgrade the Gradle and android-build-tool versions.
> 
> I will add this to the release notes or probably publish release v2.0.0 as it's a breaking change.

I upgraded rn to 70 and still getting this error.

**Comment by souvik-ghosh** [comment]
@cuteWarmFrog, Can you please make sure you followed the upgrade [guide](https://reactnative.dev/docs/upgrading)? Just updating the react-native library won't work.

**Comment by cuteWarmFrog** [comment]
I upgraded using [this tool](https://react-native-community.github.io/upgrade-helper/). It actually works with 1.51 version

**Comment by souvik-ghosh** [comment]
> I upgraded using [this tool](https://react-native-community.github.io/upgrade-helper/). It actually works with 1.51 version

@cuteWarmFrog, Sorry, you will also need to add these to the project's `build.gradle`

```
compileSdkVersion = 33
targetSdkVersion = 33
```

**Comment by cuteWarmFrog** [comment]
@souvik-ghosh I am not sure, that I am able to up these two by 2 versions but still thank you! (tried on empty project, works)

**Comment by siddharth-kt** [comment]
@souvik-ghosh thanks for the solution but is there any other solution to this since setting
`compileSdkVersion = 33
targetSdkVersion = 33`
might lead to issue with other installed libraries
I am also using react-native 0.70.

**Comment by DanielAraldi** [comment]
In React Native 0.63.4 this is also happening and we are using the most current version.

**Comment by luisdesouza10** [comment]
> In React Native 0.63.4 this is also happening and we are using the most current version.

+1

**Comment by DanielAraldi** [comment]
Any news?

**Comment by souvik-ghosh** [comment]
It is fixed in v1.6.1. Dropped support for android 13. The library continues to work with Android < 13.

**Comment by luisdesouza10** [comment]
After updating to the new version. This error is happened 

`1: Task failed with an exception.
-----------
* Where:
Build file '/Users/leader/Documents/Projetos/APP/notify_app/node_modules/react-native-create-thumbnail/android/build.gradle' line: 45

* What went wrong:
A problem occurred evaluating project ':react-native-create-thumbnail'.
> Could not find method namespace() for arguments [com.reactlibrary.createthumbnail] on extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-create-thumbnail'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================`

**Comment by luisdesouza10** [comment]
For me this error happened after update.

![Captura de Tela 2022-09-19 às 15 01 40](https://user-images.githubusercontent.com/78109065/191083606-c76a3066-a5d6-43ec-abf7-6d6ed74f2e97.png)

**Comment by DanielAraldi** [comment]
In my project RN 0.63.4 is still happening. Below is my code in `android/build.gradle`:
```gradle
buildscript {
    ext {
        buildToolsVersion = "31.0.3"
        minSdkVersion = 16
        compileSdkVersion = 31
        targetSdkVersion = 31
        googlePlayServicesVersion = "17.0.0"
        googlePlayServicesVisionVersion = "19.0.0"
        ndkVersion = "major.minor.build"
    }
```
**Note**: I updated the library version to `1.6.2` and `2.0.0-rc.2`, it still didn't work.
In both versions, in the terminal it showed me this:
```zsh
1: Task failed with an exception.
-----------
* Where:
Build file '/Users/my_user/Documents/Projects/project/project_app/node_modules/react-native-create-thumbnail/android/build.gradle' line: 45

* What went wrong:
A problem occurred evaluating project ':react-native-create-thumbnail'.
> Could not find method namespace() for arguments [com.reactlibrary.createthumbnail] on extension 'android' of type com.android.build.gradle.LibraryExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':react-native-create-thumbnail'.
> compileSdkVersion is not specified. Please add it to build.gradle
```

**Comment by souvik-ghosh** [comment]
> In my project RN 0.63.4 is still happening. Below is my code in `android/build.gradle`:
> 
> ```groovy-gradle
> buildscript {
>     ext {
>         buildToolsVersion = "31.0.3"
>         minSdkVersion = 16
>         compileSdkVersion = 31
>         targetSdkVersion = 31
>         googlePlayServicesVersion = "17.0.0"
>         googlePlayServicesVisionVersion = "19.0.0"
>         ndkVersion = "major.minor.build"
>     }
> ```
> 
> **Note**: I updated the library version to `1.6.2` and `2.0.0-rc.2`, it still didn't work. In both versions, in the terminal it showed me this:
> 
> ```shell
> 1: Task failed with an exception.
> -----------
> * Where:
> Build file '/Users/my_user/Documents/Projects/project/project_app/node_modules/react-native-create-thumbnail/android/build.gradle' line: 45
> 
> * What went wrong:
> A problem occurred evaluating project ':react-native-create-thumbnail'.
> > Could not find method namespace() for arguments [com.reactlibrary.createthumbnail] on extension 'android' of type com.android.build.gradle.LibraryExtension.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> ==============================================================================
> 
> 2: Task failed with an exception.
> -----------
> * What went wrong:
> A problem occurred configuring project ':react-native-create-thumbnail'.
> > compileSdkVersion is not specified. Please add it to build.gradle
> ```

@DanielAraldi Sorry to hear this. Could you please try **v1.6.3** and confirm if it works? looks like the `namespace` method is not supported in older Gradle versions.

**Comment by DanielAraldi** [comment]
VERSION `1.6.3` WORKED! Finally a stable version haha!

**Comment by luisdesouza10** [comment]
Version `1.6.3` still accusing:

```> Task :react-native-create-thumbnail:androidJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-create-thumbnail:androidJavadoc'.

> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/Users/leader/Documents/Projetos/APP/x/node_modules/react-native-create-thumbnail/android/build/tmp/androidJavadoc/javadoc.options'
```

**Comment by luisdesouza10** [comment]
Version `1.6.3` still accusing:

```
> Task :react-native-create-thumbnail:androidJavadoc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-create-thumbnail:androidJavadoc'.

> Javadoc generation failed. Generated Javadoc options file (useful for troubleshooting): '/x/node_modules/react-native-create-thumbnail/android/build/tmp/androidJavadoc/javadoc.options'
```

**Comment by Bimbimz** [comment]
i have this problem.
iam use "react-native": "0.70.1"
i try 1.6.3
2.0.0-rc.2
and compileSdkVersion = 33 targetSdkVersion = 33
remains the same
what is the solution?

**Comment by AlirezaHadjar** [comment]
I handled to run v1.6.3 on rn0.70 by applying the following patch
```
diff --git a/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java b/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java
index 9bd67d8..8f14cce 100644
--- a/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java
+++ b/node_modules/react-native-create-thumbnail/android/src/main/java/com/createthumbnail/CreateThumbnailModule.java
@@ -189,7 +189,11 @@ public class CreateThumbnailModule extends ReactContextBaseJavaModule {
         }
   
         Bitmap image = retriever.getFrameAtTime(time * 1000, MediaMetadataRetriever.OPTION_CLOSEST_SYNC);
-        retriever.release();
+        try {
+            retriever.release();
+        } catch(IOException e) {
+            e.printStackTrace();
+        }
         if (image == null) {
             throw new IllegalStateException("File doesn't exist or not supported");
         }

```

**Comment by Bimbimz** [comment]
> i have this problem. iam use "react-native": "0.70.1" i try 1.6.3 2.0.0-rc.2 and compileSdkVersion = 33 targetSdkVersion = 33 remains the same what is the solution?

Edit: Sorry its Work fine whiteout edit or change.

"react-native": "0.70.1"
"react-native-create-thumbnail": "^1.6.3"

**Comment by nicknamepiyapong** [comment]
> > In my project RN 0.63.4 is still happening. Below is my code in `android/build.gradle`:
> > ```
> > buildscript {
> >     ext {
> >         buildToolsVersion = "31.0.3"
> >         minSdkVersion = 16
> >         compileSdkVersion = 31
> >         targetSdkVersion = 31
> >         googlePlayServicesVersion = "17.0.0"
> >         googlePlayServicesVisionVersion = "19.0.0"
> >         ndkVersion = "major.minor.build"
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Note: I updated the library version to `1.6.2` and `2.0.0-rc.2`, it still didn't work. In both versions, in the terminal it showed me this:
> > ```shell
> > 1: Task failed with an exception.
> > -----------
> > * Where:
> > Build file '/Users/my_user/Documents/Projects/project/project_app/node_modules/react-native-create-thumbnail/android/build.gradle' line: 45
> > 
> > * What went wrong:
> > A problem occurred evaluating project ':react-native-create-thumbnail'.
> > > Could not find method namespace() for arguments [com.reactlibrary.createthumbnail] on extension 'android' of type com.android.build.gradle.LibraryExtension.
> > 
> > * Try:
> > Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> > ==============================================================================
> > 
> > 2: Task failed with an exception.
> > -----------
> > * What went wrong:
> > A problem occurred configuring project ':react-native-create-thumbnail'.
> > > compileSdkVersion is not specified. Please add it to build.gradle
> > ```
> 
> @DanielAraldi Sorry to hear this. Could you please try **v1.6.3** and confirm if it works? looks like the `namespace` method is not supported in older Gradle versions.



Can you fix it by this code?

      try {
        retriever.release();
      } catch (Exception e) { // Use general Exception here, see: https://developer.android.com/reference/android/media/MediaMetadataRetriever#release()
        // Do nothing. We can't handle this, and this is usually a system problem
      }

 please, that help me

**Comment by nicknamepiyapong** [comment]
> This got broken when the support for android 13 was added in v1.6.0. This library now requires android API level 10 or above. It's related to the change in the `MediaMetadataRetriever.release()` API (more info [here](https://developer.android.com/reference/android/media/MediaMetadataRetriever#release())).
> 
> @AlbinCederblad, The easiest solution for you would be to use v1.5.1 of this library. And to use the latest version, you can upgrade your project to react-native 69 or later, which will also upgrade the Gradle and android-build-tool versions.
> 
> I will add this to the release notes or probably publish release v2.0.0 as it's a breaking change.




Can you fix it by this code? and update new version

  try {
    retriever.release();
  } catch (Exception e) { // Use general Exception here, see: https://developer.android.com/reference/android/media/MediaMetadataRetriever#release()
    // Do nothing. We can't handle this, and this is usually a system problem
  }



please, that will help me

Because library react-native-camera-roll/camera-roll They fix it by this code too.

https://github.com/react-native-cameraroll/react-native-cameraroll/releases?page=2

**Comment by TheScalion** [comment]
"react-native-create-thumbnail": "^2.0.0-rc.2",

**Comment by izuutech** [comment]
I am having this same issue. I am on  "react-native": "0.71.7" and "react-native-create-thumbnail": "^1.6.4". I have set the compileSdkVersion and targetSdkVersion to 33 respectively and it's still not building
